/** ToolImage processing core — browser-only image work with signature validation and no server upload. */
export type ImageFormat = "image/jpeg" | "image/png" | "image/webp";
export interface ImageDetails { name: string; type: ImageFormat; width: number; height: number; size: number; }
export interface ImageJobResult { blob: Blob; previewUrl: string; width: number; height: number; format: ImageFormat; hitTarget?: boolean; alreadyWithinTarget?: boolean; }
const MAX_BYTES = 30 * 1024 * 1024; const MAX_PIXELS = 36_000_000; const MIN_TARGET_BYTES = 8 * 1024;
function matchesPrefix(bytes: Uint8Array, prefix: number[]) { return prefix.every((value, index) => bytes[index] === value); }
export async function detectImageFormat(file: File): Promise<ImageFormat> { const bytes = new Uint8Array(await file.slice(0, 16).arrayBuffer()); if (matchesPrefix(bytes, [0xff, 0xd8, 0xff])) return "image/jpeg"; if (matchesPrefix(bytes, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) return "image/png"; if (matchesPrefix(bytes, [0x52, 0x49, 0x46, 0x46]) && matchesPrefix(bytes.slice(8), [0x57, 0x45, 0x42, 0x50])) return "image/webp"; throw new Error("That file does not appear to be a supported JPG, PNG, or WebP image."); }
export function getFormatLabel(type: string) { if (type === "image/jpeg") return "JPG"; if (type === "image/png") return "PNG"; if (type === "image/webp") return "WebP"; return "Image"; }
export function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(bytes < 100 * 1024 ? 1 : 0)} KB`; return `${(bytes / 1024 / 1024).toFixed(2)} MB`; }
export async function getImageDetails(file: File): Promise<ImageDetails> { if (file.size === 0) throw new Error("This file is empty. Choose a JPG, PNG, or WebP image instead."); if (file.size > MAX_BYTES) throw new Error("This image is too large for your browser to process comfortably. Try resizing it first."); const type = await detectImageFormat(file); return new Promise((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { URL.revokeObjectURL(url); if (image.naturalWidth * image.naturalHeight > MAX_PIXELS) { reject(new Error("This image has very large dimensions for local processing. Try resizing it first.")); return; } resolve({ name: file.name, type, width: image.naturalWidth, height: image.naturalHeight, size: file.size }); }; image.onerror = () => { URL.revokeObjectURL(url); reject(new Error("We couldn’t read that image. It may be corrupted or incomplete.")); }; image.src = url; }); }
async function loadImage(file: File) { const url = URL.createObjectURL(file); const image = new Image(); image.decoding = "async"; try { await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("We couldn’t read that image. It may be corrupted or incomplete.")); image.src = url; }); return image; } finally { URL.revokeObjectURL(url); } }
function canvasToBlob(canvas: HTMLCanvasElement, type: ImageFormat, quality?: number) { return new Promise<Blob>((resolve, reject) => { canvas.toBlob((blob) => { if (blob) resolve(blob); else reject(new Error("Your browser could not create this image format. Try a smaller image or another format.")); }, type, quality); }); }
function drawToCanvas(image: HTMLImageElement, width: number, height: number, fillWhite = false) { const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(width)); canvas.height = Math.max(1, Math.round(height)); const context = canvas.getContext("2d", { alpha: !fillWhite }); if (!context) throw new Error("Your browser could not prepare the image workspace."); if (fillWhite) { context.fillStyle = "#ffffff"; context.fillRect(0, 0, canvas.width, canvas.height); } context.imageSmoothingEnabled = true; context.imageSmoothingQuality = "high"; context.drawImage(image, 0, 0, canvas.width, canvas.height); return canvas; }
const safePreview = (blob: Blob) => URL.createObjectURL(blob); const yieldToBrowser = () => new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
export async function compressToTarget(file: File, targetBytes: number, sourceFormat: ImageFormat): Promise<ImageJobResult> { if (targetBytes < MIN_TARGET_BYTES) throw new Error("Choose a target of at least 8 KB."); const image = await loadImage(file); if (targetBytes >= file.size) return { blob: file, previewUrl: safePreview(file), width: image.naturalWidth, height: image.naturalHeight, format: sourceFormat, hitTarget: true, alreadyWithinTarget: true }; const outputType: ImageFormat = sourceFormat === "image/png" ? "image/webp" : "image/jpeg"; const initialWidth = image.naturalWidth; const initialHeight = image.naturalHeight; let scale = 1; let bestBlob: Blob | null = null; let bestWidth = initialWidth; let bestHeight = initialHeight; for (let pass = 0; pass < 7; pass += 1) { const width = Math.max(160, Math.round(initialWidth * scale)); const height = Math.max(160, Math.round(initialHeight * scale)); const canvas = drawToCanvas(image, width, height, outputType === "image/jpeg"); let low = 0.08; let high = 0.96; let candidate: Blob | null = null; for (let attempt = 0; attempt < 9; attempt += 1) { const quality = (low + high) / 2; const blob = await canvasToBlob(canvas, outputType, quality); if (!bestBlob || blob.size < bestBlob.size) { bestBlob = blob; bestWidth = width; bestHeight = height; } if (blob.size <= targetBytes) { candidate = blob; low = quality; } else high = quality; } if (candidate) return { blob: candidate, previewUrl: safePreview(candidate), width, height, format: outputType, hitTarget: true }; scale *= 0.82; await yieldToBrowser(); } if (!bestBlob) throw new Error("We couldn’t create a compressed version of this image."); return { blob: bestBlob, previewUrl: safePreview(bestBlob), width: bestWidth, height: bestHeight, format: outputType, hitTarget: bestBlob.size <= targetBytes }; }
export async function resizeImage(file: File, width: number, height: number, sourceFormat: ImageFormat): Promise<ImageJobResult> { const image = await loadImage(file); const canvas = drawToCanvas(image, width, height, sourceFormat === "image/jpeg"); const blob = await canvasToBlob(canvas, sourceFormat, sourceFormat === "image/png" ? undefined : 0.92); return { blob, previewUrl: safePreview(blob), width: canvas.width, height: canvas.height, format: sourceFormat }; }
export async function convertImage(file: File, format: ImageFormat): Promise<ImageJobResult> { const image = await loadImage(file); const canvas = drawToCanvas(image, image.naturalWidth, image.naturalHeight, format === "image/jpeg"); const blob = await canvasToBlob(canvas, format, format === "image/png" ? undefined : 0.92); return { blob, previewUrl: safePreview(blob), width: canvas.width, height: canvas.height, format }; }
export function downloadResult(blob: Blob, originalName: string, format: ImageFormat) { const extension = format === "image/jpeg" ? "jpg" : format.split("/")[1]; const stem = ((originalName.replace(/\.[^/.]+$/, "") || "toolimage").replace(/[^a-z0-9_-]+/gi, "-").replace(/^-+|-+$/g, "").slice(0, 80)) || "toolimage"; const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${stem}-toolimage.${extension}`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
