import { beforeEach, describe, expect, it, vi } from "vitest";
import { createHmac } from "node:crypto";

const mocks = vi.hoisted(() => ({ from: vi.fn() }));
vi.mock("../../../api/_lib/supabase.js", () => ({ adminSupabase: () => ({ from: mocks.from }) }));

import webhookHandler from "../../../api/webhooks/razorpay";

const secret = "test_webhook_secret";
const subscriptionId = "sub_owner";
const future = Math.floor(Date.now() / 1000) + 86400;
const past = Math.floor(Date.now() / 1000) - 60;

type DatabaseState = { insertError?: { code?: string } | null; paymentSession?: unknown; existingEntitlement?: unknown; upserts: unknown[]; updates: unknown[] };

function responseMock() { const recorded = { statusCode: 200, body: null as unknown }; const response = { status(code: number) { recorded.statusCode = code; return response; }, json(body: unknown) { recorded.body = body; return response; }, setHeader() { return response; } } as unknown as VercelResponse; return { response, recorded }; }
function webhookEvent(status: string, currentEnd: number, createdAt = 1_787_314_000, changes = false) { return { event: `subscription.${status === "active" ? "activated" : status}`, created_at: createdAt, payload: { subscription: { entity: { id: subscriptionId, plan_id: "plan_live", customer_id: "cust_hidden", status, current_end: currentEnd, has_scheduled_changes: changes } } } }; }
function requestMock(event: unknown, eventId = "evt_lifecycle") { const raw = Buffer.from(JSON.stringify(event)); const signature = createHmac("sha256", secret).update(raw).digest("hex"); return { method: "POST", headers: { "x-razorpay-signature": signature, "x-razorpay-event-id": eventId }, async *[Symbol.asyncIterator]() { yield raw; } } as unknown as VercelRequest; }
function database(state: DatabaseState) { mocks.from.mockImplementation((table: string) => ({ insert: vi.fn(async () => ({ error: table === "razorpay_webhook_events" ? state.insertError ?? null : null })), select: vi.fn(() => ({ eq: vi.fn(() => ({ maybeSingle: vi.fn(async () => ({ data: table === "payment_sessions" ? state.paymentSession ?? null : state.existingEntitlement ?? null, error: null })) })) })), upsert: vi.fn(async (payload) => { state.upserts.push({ table, payload }); return { error: null }; }), update: vi.fn((payload) => { state.updates.push({ table, payload }); return { eq: vi.fn(async () => ({ error: null })) }; }) })); }

beforeEach(() => { vi.clearAllMocks(); process.env.RAZORPAY_WEBHOOK_SECRET = secret; });

describe("verified Razorpay subscription lifecycle webhooks", () => {
  it("persists an external cancellation as cycle-end access while a paid period remains", async () => { const state: DatabaseState = { paymentSession: { user_id: "user_owner" }, upserts: [], updates: [] }; database(state); const { response, recorded } = responseMock(); await webhookHandler(requestMock(webhookEvent("cancelled", future), "evt_cancelled"), response); expect(recorded.statusCode).toBe(200); expect(state.upserts).toContainEqual(expect.objectContaining({ table: "entitlements", payload: expect.objectContaining({ status: "grace", lifecycle_state: "cancel_at_cycle_end", cancel_at_cycle_end: true, provider_status: "cancelled" }) })); });
  it("persists external pending, halted, paused, resumed, and completion lifecycle states", async () => { for (const [status, period, expectedLifecycle, expectedAccess] of [["pending", future, "pending", "grace"], ["halted", past, "halted", "inactive"], ["paused", future, "paused", "grace"], ["active", future, "active", "pro"], ["completed", past, "ended", "inactive"]] as const) { const state: DatabaseState = { paymentSession: { user_id: "user_owner" }, upserts: [], updates: [] }; database(state); const { response, recorded } = responseMock(); await webhookHandler(requestMock(webhookEvent(status, period), `evt_${status}`), response); expect(recorded.statusCode).toBe(200); expect(state.upserts).toContainEqual(expect.objectContaining({ table: "entitlements", payload: expect.objectContaining({ lifecycle_state: expectedLifecycle, status: expectedAccess, provider_verification_error_at: null }) })); } });
  it("treats repeated Razorpay event IDs as idempotent duplicates", async () => { const state: DatabaseState = { insertError: { code: "23505" }, paymentSession: { user_id: "user_owner" }, upserts: [], updates: [] }; database(state); const { response, recorded } = responseMock(); await webhookHandler(requestMock(webhookEvent("active", future), "evt_duplicate"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toEqual({ received: true, duplicate: true }); expect(state.upserts).toEqual([]); });
  it("does not allow an older event to roll a newer lifecycle state backward", async () => { const state: DatabaseState = { paymentSession: { user_id: "user_owner" }, existingEntitlement: { user_id: "user_owner", provider_event_at: "2026-08-21T12:00:00.000Z" }, upserts: [], updates: [] }; database(state); const { response, recorded } = responseMock(); await webhookHandler(requestMock(webhookEvent("cancelled", future, 1_787_300_000), "evt_stale"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toEqual({ received: true, stale: true }); expect(state.upserts).toEqual([]); });
  it("does not create an entitlement for an unknown subscription reference", async () => { const state: DatabaseState = { paymentSession: null, existingEntitlement: null, upserts: [], updates: [] }; database(state); const { response, recorded } = responseMock(); await webhookHandler(requestMock(webhookEvent("active", future), "evt_unknown"), response); expect(recorded.statusCode).toBe(200); expect(state.upserts).toEqual([]); });
  it("rejects an invalid signature before storing webhook state", async () => { const state: DatabaseState = { upserts: [], updates: [] }; database(state); const event = webhookEvent("active", future); const raw = Buffer.from(JSON.stringify(event)); const request = { method: "POST", headers: { "x-razorpay-signature": "invalid", "x-razorpay-event-id": "evt_bad" }, async *[Symbol.asyncIterator]() { yield raw; } } as unknown as VercelRequest; const { response, recorded } = responseMock(); await webhookHandler(request, response); expect(recorded.statusCode).toBe(400); expect(state.upserts).toEqual([]); expect(mocks.from).not.toHaveBeenCalled(); });
});
