/** ToolImage SEO registry — one canonical source for route-specific metadata and useful keyword-page copy. */
export const SITE_URL = "https://toolimage.online";
export const DEFAULT_SOCIAL_IMAGE = "/assets/toolimage-hero-compression.webp";
export interface PageSeo { title: string; description: string; path: string; heading?: React.ReactNode; guideTitle?: string; guide?: string; targetBytes?: number; detail?: string; }
export const SEO_PAGES = {
  compressJpg: { title: "Compress JPG Online — Private, Local Image Compression | ToolImage", description: "Compress JPG images in your browser. Choose a target size, preserve practical quality, and download without uploading your image.", path: "/compress-jpg", heading: <>Compress JPGs.<br /><em>Keep the detail.</em></>, guideTitle: "How to compress a JPG online", guide: "Upload a JPG, select a target size, and let ToolImage search locally for the highest practical quality that meets it. Your image is processed in this browser, then made ready to download.", detail: "JPG files are exported as JPG during target-size compression for familiar, photo-friendly results." },
  compressPng: { title: "Compress PNG Online — Private PNG to WebP Compression | ToolImage", description: "Compress PNG images in your browser. ToolImage creates a compact WebP when a smaller target file is needed, while preserving transparency where supported.", path: "/compress-png", heading: <>Compress PNGs.<br /><em>Keep transparency.</em></>, guideTitle: "How to compress a PNG without uploading it", guide: "PNG is a lossless format, so it has no browser quality setting to turn down. For targeted compression, ToolImage creates a WebP result locally, which can retain transparent areas while making a significantly smaller file.", detail: "For a specific target size, PNG uploads create a WebP result locally. Use Convert if you need to keep a PNG file." },
  compressWebp: { title: "Compress WebP Online — Reduce WebP File Size Locally | ToolImage", description: "Reduce WebP image size in your browser with a chosen target size. No upload, no account, and a practical quality-first compression approach.", path: "/compress-webp", heading: <>Compress WebP.<br /><em>Stay compact.</em></>, guideTitle: "How to reduce WebP file size", guide: "WebP is already an efficient modern format. ToolImage still checks local quality and dimensions iteratively to approach the target size without making unnecessary reductions." },
  compress20kb: { title: "Compress Image to 20 KB — Private Online Tool | ToolImage", description: "Make an image close to 20 KB in your browser. ToolImage balances quality and dimensions locally, then explains when 20 KB is not practical.", path: "/compress-image-to-20kb", heading: <>Make an image<br /><em>20 KB.</em></>, guideTitle: "How to make an image 20 KB", guide: "Choose 20 KB and upload a supported image. Very small targets depend on the source dimensions and visual detail, so ToolImage returns the closest practical result when reaching 20 KB would overly reduce the image.", targetBytes: 20 * 1024 },
  compress50kb: { title: "Compress Image to 50 KB — Free Local Tool | ToolImage", description: "Compress an image to 50 KB in your browser. Select the target, keep processing local, and download the closest practical result.", path: "/compress-image-to-50kb", heading: <>Make an image<br /><em>50 KB.</em></>, guideTitle: "How to make an image 50 KB", guide: "Upload a JPG, PNG, or WebP image and set the target to 50 KB. ToolImage tests local quality settings first, then carefully reduces dimensions only when it is needed.", targetBytes: 50 * 1024 },
  compress100kb: { title: "Compress Image to 100 KB — Browser-Based Tool | ToolImage", description: "Reduce an image to 100 KB locally in your browser. ToolImage finds a practical balance between file size, dimensions, and visual quality.", path: "/compress-image-to-100kb", heading: <>Make an image<br /><em>100 KB.</em></>, guideTitle: "How to make an image 100 KB", guide: "A 100 KB target often leaves more room for useful detail than the smallest targets. ToolImage uses a local quality search and reports the closest practical version if the exact size is not possible.", targetBytes: 100 * 1024 },
  compress200kb: { title: "Compress Image to 200 KB — Private Image Tool | ToolImage", description: "Compress an image to 200 KB in your browser. No account or image upload is required for ToolImage’s local processing workflow.", path: "/compress-image-to-200kb", heading: <>Make an image<br /><em>200 KB.</em></>, guideTitle: "How to make an image 200 KB", guide: "Choose 200 KB when you need a smaller, shareable image while keeping more visual information. ToolImage works locally and preserves as much practical quality as the target allows.", targetBytes: 200 * 1024 },
} satisfies Record<string, PageSeo>;
export function absoluteUrl(path: string) { return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`; }
