import type { VercelRequest, VercelResponse } from "@vercel/node";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ requireUser: vi.fn(), from: vi.fn(), fetchSubscription: vi.fn(), cancelSubscription: vi.fn() }));
vi.mock("../../../api/_lib/supabase.js", () => ({ requireUser: mocks.requireUser, adminSupabase: () => ({ from: mocks.from }) }));
vi.mock("../../../api/_lib/razorpay.js", () => ({ razorpay: () => ({ subscriptions: { fetch: mocks.fetchSubscription, cancel: mocks.cancelSubscription } }) }));

import cancelHandler from "../../../api/subscriptions/cancel";
import statusHandler from "../../../api/subscriptions/status";
import { TOOLIMAGE_PRO_PLAN_ID } from "../../../api/_lib/toolimageProPlan";

const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);

function responseMock() { const recorded = { statusCode: 200, body: null as unknown }; const response = { status(code: number) { recorded.statusCode = code; return response; }, json(body: unknown) { recorded.body = body; return response; }, setHeader() { return response; } } as unknown as VercelResponse; return { response, recorded }; }
function requestMock(method: "GET" | "POST") { return { method, headers: { authorization: "Bearer test" } } as unknown as VercelRequest; }
function databaseWith(entitlement: unknown) { const update = vi.fn(() => ({ eq: vi.fn(() => ({ eq: vi.fn(async () => ({ error: null })) })) })); mocks.from.mockReturnValue({ select: vi.fn(() => ({ eq: vi.fn(() => ({ maybeSingle: vi.fn(async () => ({ data: entitlement, error: null })) })) })), update }); return { update }; }

beforeEach(() => { vi.clearAllMocks(); consoleError.mockClear(); mocks.requireUser.mockResolvedValue({ id: "user_owner" }); });

describe("subscription management API", () => {
  it("returns only the signed-in user’s recorded provider subscription", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: 1789824000 }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { plan: "ToolImage Pro", price: "₹149/month", status: "active" } }); });
  it("returns a confirmed inactive provider subscription without granting Pro", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "inactive", current_end: 1 }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { status: "inactive", providerStatus: "inactive", nextBillingAt: "1970-01-01T00:00:01.000Z" } }); });
  it("preserves the deployed 500 response for a Razorpay non-2xx error object", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockRejectedValue({ statusCode: 401, error: { code: "BAD_REQUEST_ERROR", description: "provider detail must not reach the client" } }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(500); expect(recorded.body).toEqual({ error: "Unexpected server error" }); });
  it("logs only redacted safe metadata for a Razorpay non-2xx error while preserving the deployed response", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockRejectedValue({ statusCode: 401, error: { code: "BAD_REQUEST_ERROR", description: "Request for sub_hidden cust_hidden pay_hidden rzp_live_abcdefghijklmnopqrstuvwxyz user@example.com Authorization: Bearer hidden-token", reason: "invalid_request", source: "business", step: "subscription_fetch", metadata: { subscription_id: "sub_hidden", customer_id: "cust_hidden", payment_id: "pay_hidden" } } }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(500); expect(recorded.body).toEqual({ error: "Unexpected server error" }); expect(consoleError).toHaveBeenCalledWith("[Subscription status] Razorpay fetch failed", expect.objectContaining({ providerHttpStatus: 401, razorpayErrorCode: "BAD_REQUEST_ERROR", providerErrorReason: "invalid_request", providerErrorSource: "business", providerErrorStep: "subscription_fetch", sdkErrorType: "object", sdkErrorName: null })); const serializedLog = JSON.stringify(consoleError.mock.calls); expect(serializedLog).toContain("[redacted]"); expect(serializedLog).not.toContain("sub_hidden"); expect(serializedLog).not.toContain("cust_hidden"); expect(serializedLog).not.toContain("pay_hidden"); expect(serializedLog).not.toContain("rzp_live_"); expect(serializedLog).not.toContain("user@example.com"); expect(serializedLog).not.toContain("Authorization"); expect(serializedLog).not.toContain("hidden-token"); expect(serializedLog).not.toContain("metadata"); });
  it("preserves the deployed ownership-error response for a malformed provider payload without logging payload fields", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_hidden", plan_id: TOOLIMAGE_PRO_PLAN_ID, metadata: { customer_id: "cust_hidden" } }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(500); expect(recorded.body).toEqual({ error: "Subscription ownership could not be confirmed." }); expect(consoleError).not.toHaveBeenCalled(); });
  it("preserves the deployed provider SDK exception response while logging only its safe type and name", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockRejectedValue(new Error("provider exception must not reach the client")); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(500); expect(recorded.body).toEqual({ error: "provider exception must not reach the client" }); expect(consoleError).toHaveBeenCalledWith("[Subscription status] Razorpay fetch failed", { providerHttpStatus: null, razorpayErrorCode: null, providerErrorDescription: null, providerErrorReason: null, providerErrorSource: null, providerErrorStep: null, sdkErrorType: "object", sdkErrorName: "Error" }); });
  it("keeps authentication failures distinct from provider lookup failures", async () => { mocks.requireUser.mockRejectedValueOnce(new Error("Unauthorized")); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(401); expect(recorded.body).toEqual({ error: "Unauthorized" }); });
  it("returns no subscription when the signed-in user has no entitlement record", async () => { databaseWith(null); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toEqual({ subscription: null }); expect(mocks.fetchSubscription).not.toHaveBeenCalled(); });
  it("sends a cycle-end cancellation only for the server-recorded owned subscription", async () => { const { update } = databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: 1789824000 }); mocks.cancelSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: 1789824000, has_scheduled_changes: true }); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(mocks.cancelSubscription).toHaveBeenCalledWith("sub_owner", true); expect(update).toHaveBeenCalledOnce(); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ cancelled: true, cancellationPending: true, status: "cancellation_pending" }); });
  it("refuses a mismatched provider subscription and never calls cancellation", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_other", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active" }); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(mocks.cancelSubscription).not.toHaveBeenCalled(); expect(recorded.statusCode).toBe(400); expect(recorded.body).toEqual({ error: "Subscription ownership could not be confirmed." }); });
  it("refuses cancellation for an expired server-confirmed subscription", async () => { databaseWith({ razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID }); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "expired", current_end: 1 }); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(mocks.cancelSubscription).not.toHaveBeenCalled(); expect(recorded.statusCode).toBe(400); expect(recorded.body).toEqual({ error: "Only an active Pro subscription can be cancelled." }); });
});
