import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ requireUser: vi.fn(), from: vi.fn(), fetchSubscription: vi.fn(), cancelSubscription: vi.fn() }));
vi.mock("../../../api/_lib/supabase.js", () => ({ requireUser: mocks.requireUser, adminSupabase: () => ({ from: mocks.from }) }));
vi.mock("../../../api/_lib/razorpay.js", () => ({ razorpay: () => ({ subscriptions: { fetch: mocks.fetchSubscription, cancel: mocks.cancelSubscription } }) }));

import cancelHandler from "../../../api/subscriptions/cancel";
import statusHandler from "../../../api/subscriptions/status";
import { TOOLIMAGE_PRO_PLAN_ID } from "../../../api/_lib/toolimageProPlan";

const future = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
const activeEntitlement = { status: "pro", razorpay_subscription_id: "sub_owner", razorpay_plan_id: TOOLIMAGE_PRO_PLAN_ID, provider_status: "active", current_period_end: future, lifecycle_state: "active", cancel_at_cycle_end: false, provider_verification_error_at: null };

function responseMock() { const recorded = { statusCode: 200, body: null as unknown }; const response = { status(code: number) { recorded.statusCode = code; return response; }, json(body: unknown) { recorded.body = body; return response; }, setHeader() { return response; } } as unknown as VercelResponse; return { response, recorded }; }
function requestMock(method: "GET" | "POST") { return { method, headers: { authorization: "Bearer test" } } as unknown as VercelRequest; }
function databaseWith(entitlement: unknown, options: { readError?: unknown; updateError?: unknown } = {}) { const update = vi.fn(() => ({ eq: vi.fn(() => ({ eq: vi.fn(async () => ({ error: options.updateError ?? null })) })) })); mocks.from.mockReturnValue({ select: vi.fn(() => ({ eq: vi.fn(() => ({ maybeSingle: vi.fn(async () => ({ data: entitlement, error: options.readError ?? null })) })) })), update }); return { update }; }

beforeEach(() => { vi.clearAllMocks(); mocks.requireUser.mockResolvedValue({ id: "user_owner" }); });

describe("server-confirmed subscription management API", () => {
  it("renders an active subscription from server state without a Razorpay fetch", async () => { databaseWith(activeEntitlement); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { plan: "ToolImage Pro", price: "₹149/month", status: "active", nextBillingAt: future, verificationError: false } }); expect(mocks.fetchSubscription).not.toHaveBeenCalled(); });
  it("returns the persisted next billing date and scheduled cycle-end cancellation without a Razorpay fetch", async () => { databaseWith({ ...activeEntitlement, status: "grace", lifecycle_state: "cancel_at_cycle_end", cancel_at_cycle_end: true, provider_status: "cancelled" }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { status: "cancellation_pending", cancellationPending: true, nextBillingAt: future } }); expect(mocks.fetchSubscription).not.toHaveBeenCalled(); });
  it("returns no subscription for a signed-in Free account", async () => { databaseWith(null); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toEqual({ subscription: null, verificationError: false }); expect(mocks.fetchSubscription).not.toHaveBeenCalled(); });
  it("keeps a known active server state active when provider verification is unavailable", async () => { databaseWith({ ...activeEntitlement, provider_verification_error_at: new Date().toISOString() }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { status: "active", verificationError: true }, verificationError: true }); expect(mocks.fetchSubscription).not.toHaveBeenCalled(); });
  it("returns a distinct safe verification error for unknown server state without exposing provider details", async () => { databaseWith({ status: "inactive", razorpay_subscription_id: "sub_owner", provider_status: null, current_period_end: null, lifecycle_state: null, cancel_at_cycle_end: false, provider_verification_error_at: new Date().toISOString() }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ subscription: { status: "verification_error", verificationError: true }, verificationError: true, verificationMessage: "We’re having trouble verifying your subscription. Please try again later." }); expect(JSON.stringify(recorded.body)).not.toContain("sub_owner"); });
  it("returns a deterministic safe verification error for a server read timeout or provider-like failure", async () => { databaseWith(null, { readError: new Error("rzp_live_sensitive provider failure") }); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(503); expect(recorded.body).toEqual({ subscription: null, verificationError: true, error: "We’re having trouble verifying your subscription. Please try again later." }); expect(JSON.stringify(recorded.body)).not.toContain("rzp_live"); });
  it("keeps authentication failures distinct", async () => { mocks.requireUser.mockRejectedValueOnce(new Error("Unauthorized")); const { response, recorded } = responseMock(); await statusHandler(requestMock("GET"), response); expect(recorded.statusCode).toBe(401); expect(recorded.body).toEqual({ error: "Unauthorized" }); });
  it("sends a cycle-end cancellation only for the server-recorded owned subscription", async () => { const { update } = databaseWith(activeEntitlement); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: Math.floor(Date.now() / 1000) + 86400 }); mocks.cancelSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: Math.floor(Date.now() / 1000) + 86400, has_scheduled_changes: true }); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(mocks.cancelSubscription).toHaveBeenCalledWith("sub_owner", true); expect(update).toHaveBeenCalledOnce(); expect(recorded.statusCode).toBe(200); expect(recorded.body).toMatchObject({ cancelled: true, cancellationPending: true, status: "cancellation_pending" }); });
  it("preserves local state and returns only the safe message when provider cancellation fails", async () => { const { update } = databaseWith(activeEntitlement); mocks.fetchSubscription.mockResolvedValue({ id: "sub_owner", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active", current_end: Math.floor(Date.now() / 1000) + 86400 }); mocks.cancelSubscription.mockRejectedValue(new Error("provider payment identifier pay_hidden")); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(update).not.toHaveBeenCalled(); expect(recorded.statusCode).toBe(503); expect(recorded.body).toEqual({ error: "We’re having trouble verifying your subscription. Please try again later." }); expect(JSON.stringify(recorded.body)).not.toContain("pay_hidden"); });
  it("rejects a cross-user or mismatched provider subscription before cancellation", async () => { databaseWith(activeEntitlement); mocks.fetchSubscription.mockResolvedValue({ id: "sub_other", plan_id: TOOLIMAGE_PRO_PLAN_ID, status: "active" }); const { response, recorded } = responseMock(); await cancelHandler(requestMock("POST"), response); expect(mocks.cancelSubscription).not.toHaveBeenCalled(); expect(recorded.statusCode).toBe(403); expect(recorded.body).toEqual({ error: "Subscription ownership could not be confirmed." }); });
});
