import type { VercelRequest, VercelResponse } from "@vercel/node";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import supportHandler from "../../../api/support";
import { SUPPORT_ISSUE_TYPES } from "../../../shared/support";

const original = { resend: process.env.RESEND_API_KEY, to: process.env.SUPPORT_TO_EMAIL, from: process.env.SUPPORT_FROM_EMAIL, redisUrl: process.env.UPSTASH_REDIS_REST_URL, redisToken: process.env.UPSTASH_REDIS_REST_TOKEN };
const completeReport = { email: "person@example.com", issueType: SUPPORT_ISSUE_TYPES[0], description: "The image resize action fails after I select a supported image file.", pageUrl: "https://toolimage.online/resize-image", browser: "Vitest browser" };
function responseMock() { const recorded = { statusCode: 200, body: null as unknown, headers: {} as Record<string, string> }; const response = { status(code: number) { recorded.statusCode = code; return response; }, json(body: unknown) { recorded.body = body; return response; }, setHeader(name: string, value: string) { recorded.headers[name] = value; } } as unknown as VercelResponse; return { response, recorded }; }
function requestMock(body: Record<string, unknown>) { return { method: "POST", headers: { "x-forwarded-for": "198.51.100.101" }, body, socket: { remoteAddress: "198.51.100.101" } } as unknown as VercelRequest; }
beforeEach(() => { process.env.RESEND_API_KEY = "server-test-key"; process.env.SUPPORT_TO_EMAIL = "nt203197@gmail.com"; process.env.SUPPORT_FROM_EMAIL = "support@toolimage.online"; process.env.UPSTASH_REDIS_REST_URL = "https://upstash.example"; process.env.UPSTASH_REDIS_REST_TOKEN = "server-test-token"; });
afterEach(() => { vi.unstubAllGlobals(); process.env.RESEND_API_KEY = original.resend; process.env.SUPPORT_TO_EMAIL = original.to; process.env.SUPPORT_FROM_EMAIL = original.from; process.env.UPSTASH_REDIS_REST_URL = original.redisUrl; process.env.UPSTASH_REDIS_REST_TOKEN = original.redisToken; });

describe("support API", () => {
  it("delivers a valid report through server-side Resend only after durable rate-limit consumption", async () => { const fetchMock = vi.fn(async (input: string) => input.includes("/multi-exec") ? new Response(JSON.stringify([{ result: 1 }, { result: 1 }]), { status: 200 }) : new Response(JSON.stringify({ id: "email_test_id" }), { status: 200 })); vi.stubGlobal("fetch", fetchMock); const { response, recorded } = responseMock(); await supportHandler(requestMock(completeReport), response); expect(recorded.statusCode).toBe(201); expect(recorded.body).toEqual({ delivered: true }); expect(fetchMock).toHaveBeenCalledTimes(2); expect(fetchMock).toHaveBeenLastCalledWith("https://api.resend.com/emails", expect.objectContaining({ headers: expect.objectContaining({ Authorization: "Bearer server-test-key" }) })); });
  it("rejects malformed reports without invoking Resend", async () => { const fetchMock = vi.fn(async () => new Response(JSON.stringify([{ result: 1 }, { result: 1 }]), { status: 200 })); vi.stubGlobal("fetch", fetchMock); const { response, recorded } = responseMock(); await supportHandler(requestMock({ ...completeReport, description: "short" }), response); expect(recorded.statusCode).toBe(400); expect(recorded.body).toEqual({ error: "Please describe the issue in at least 20 characters." }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("returns a safe 429 response without sending when the durable limit is exhausted", async () => { const fetchMock = vi.fn(async () => new Response(JSON.stringify([{ result: 6 }, { result: 0 }]), { status: 200 })); vi.stubGlobal("fetch", fetchMock); const { response, recorded } = responseMock(); await supportHandler(requestMock(completeReport), response); expect(recorded.statusCode).toBe(429); expect(recorded.headers["Retry-After"]).toBe("900"); expect(recorded.body).toEqual({ error: "Please wait before sending another report." }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("returns an honest delivery-unavailable response when Resend rejects the report", async () => { const fetchMock = vi.fn(async (input: string) => input.includes("/multi-exec") ? new Response(JSON.stringify([{ result: 1 }, { result: 1 }]), { status: 200 }) : new Response("provider failure", { status: 503 })); vi.stubGlobal("fetch", fetchMock); const { response, recorded } = responseMock(); await supportHandler(requestMock(completeReport), response); expect(recorded.statusCode).toBe(502); expect(recorded.body).toEqual({ error: "We could not deliver your report right now. Please try again later." }); });
});
