import type { VercelRequest, VercelResponse } from "@vercel/node";
import { apiError, method, readJson } from "../_lib/http.js";
import { isRegionalPriceId, REGIONAL_PRICE_CONFIG } from "../_lib/pricing.js";
import { planForCurrency, razorpay, razorpayKeyId } from "../_lib/razorpay.js";
import { adminSupabase, requireUser } from "../_lib/supabase.js";
import { TOOLIMAGE_PRO } from "../../shared/proSubscription.js";
import { TOOLIMAGE_PRO_PLAN_ID } from "../_lib/toolimageProPlan.js";

export default async function handler(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; try { const user = await requireUser(req); const body = await readJson(req); if (body.region !== "india" || !isRegionalPriceId(body.region)) throw new Error("ToolImage Pro is currently available in INR only."); const regional = REGIONAL_PRICE_CONFIG[body.region]; const planId = planForCurrency(regional.currency); if (planId !== TOOLIMAGE_PRO_PLAN_ID) throw new Error("The configured Razorpay plan does not match the verified ToolImage Pro plan."); const provider = razorpay(); const subscription = await provider.subscriptions.create({ plan_id: planId, total_count: 120, quantity: 1, customer_notify: 1, notes: { toolimage_user_id: user.id, display_region: body.region } }) as { id: string }; const { error } = await adminSupabase().from("payment_sessions").insert({ user_id: user.id, razorpay_subscription_id: subscription.id, razorpay_plan_id: planId, display_region: body.region }); if (error) throw error; res.status(201).json({ subscriptionId: subscription.id, keyId: razorpayKeyId(), name: TOOLIMAGE_PRO.name, description: `${TOOLIMAGE_PRO.priceWithInterval} · recurring monthly billing` }); } catch (error) { apiError(res, error, error instanceof Error && error.message === "Unauthorized" ? 401 : 500); } }
