/** ToolImage pricing — Monochrome Instrument: transparent feature framing without a simulated checkout. */
/** ToolImage pricing — Monochrome Instrument: clear availability language, no fake checkout, and honest future value. */
import { Check } from "lucide-react";
import { Link } from "wouter";
import { SiteShell } from "@/components/SiteShell";
import { Seo } from "@/components/Seo";

const freeItems = ["Image compression and target-size compression", "Exact image resizing", "JPG, PNG, and WebP conversion", "Client-side processing", "No account required"];
const proItems = ["Batch processing and multiple-image workflows", "Advanced compression controls and export options", "Saved and custom resize presets", "Bulk format conversion and batch download", "Processing history when accounts are introduced"];

export default function Pricing() { return <SiteShell><Seo title="ToolImage Pricing — Free Local Image Tools" description="ToolImage’s core image compression, resize, and conversion tools are free and run locally in your browser." path="/pricing" noIndex /><main id="main-content"><section className="pricing-hero"><div className="pricing-rail"><span>01</span><i /><span>CAPABILITY INDEX</span><small>NO PAYMENT FLOW ACTIVE</small></div><p className="eyebrow">SIMPLE BY DESIGN</p><h1>Useful now.<br /><em>More when it matters.</em></h1><p>Every core tool is free, works locally in your browser, and does not require an account.</p></section><section className="capability-sheet"><div className="capability-sheet__header"><span className="eyebrow">SERVICE SPECIFICATION</span><span>STATUS / AUG 2026</span></div><article className="capability-row"><div className="capability-row__number">01</div><div><p className="eyebrow">AVAILABLE NOW</p><h2>Free</h2><p>The local toolset for making a single image fit without handing it to a server.</p></div><div className="capability-row__price"><strong>₹0</strong><span>forever</span></div><ul>{freeItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href="/compress-image" className="primary-button">Use ToolImage</Link></article><article className="capability-row capability-row--future"><div className="capability-row__number">02</div><div><p className="eyebrow">COMING SOON</p><h2>ToolImage Pro</h2><p>A future premium workflow for people processing more than one image at a time.</p></div><div className="capability-row__price"><span>Future tier</span></div><ul>{proItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><button type="button" className="secondary-button" disabled>Coming soon</button></article></section><section className="pricing-note"><span>NO SURPRISES</span><i /><p>ToolImage will never suggest a payment is available before a real, secure purchase flow exists.</p></section></main></SiteShell>; }
