import { Check, LoaderCircle, LockKeyhole } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import { Link } from "wouter";
import { ProAccessPanel } from "@/components/ProAccessPanel";
import { ProWelcomeCard } from "@/components/ProWelcomeCard";
import { useEntitlement } from "@/contexts/EntitlementContext";
import { loadRazorpay } from "@/lib/razorpayCheckout";
import { createCheckout } from "@/lib/checkoutPreflight";
import { SiteShell } from "@/components/SiteShell";
import { Seo } from "@/components/Seo";

const freeItems = ["Single-image and target-size compression", "Single-image resizing with manual pixels", "Single-image JPG, PNG, and WebP conversion", "Standard presets and client-side processing"];
const proItems = ["Batch processing", "Custom saved presets", "Download batches as ZIP"];

export default function Pricing() {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const reduceMotion = useReducedMotion(); const { configured, user, isPro, refresh } = useEntitlement();
  const checkout = async () => { setMessage(null); setBusy(true); try { const currentSession = await refresh(); const token = currentSession?.access_token; const data = await createCheckout(token, fetch, { region: "india" }); await loadRazorpay(); new window.Razorpay!({ key: data.keyId, subscription_id: data.subscriptionId, name: data.name || "ToolImage Pro", description: data.description || "₹149/month", handler: async (response) => { const verified = await fetch("/api/subscriptions/verify", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ subscriptionId: response.razorpay_subscription_id, paymentId: response.razorpay_payment_id, signature: response.razorpay_signature }) }); const result = await verified.json() as { active?: boolean; error?: string }; if (!verified.ok) { setMessage(result.error || "We could not verify this payment."); return; } await refresh(); setMessage(result.active ? "Welcome to ToolImage Pro." : "Payment verified. Your subscription is waiting for Razorpay activation."); }, modal: { ondismiss: () => setMessage("Checkout was cancelled. No Pro access was granted.") }, theme: { color: "#0d786d" } }).open(); } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout could not be started."); } finally { setBusy(false); } };
  return <SiteShell><Seo title="ToolImage Pricing — Free Local Image Tools" description="ToolImage’s core image compression, resize, and conversion tools are free and run locally in your browser." path="/pricing" noIndex /><main id="main-content"><section className="pricing-hero pricing-hero--regional"><div className="pricing-rail"><span>01</span><i /><span>CAPABILITY INDEX</span><small>INR / VERIFIED ACCESS</small></div><p className="eyebrow">SIMPLE BY DESIGN</p><h1>Useful now.<br /><em>More when it matters.</em></h1><p>Every core tool is free, works locally in your browser, and does not require an account.</p></section>{isPro && <ProWelcomeCard />}<section className="pricing-cards"><motion.article className="pricing-card pricing-card--free" initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.28 }}><p className="eyebrow">AVAILABLE NOW</p><h2>Free</h2><p>For everyday image tasks.</p><div className="pricing-card__price"><strong>Free</strong><span>No account required</span></div><ul>{freeItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href="/" className="primary-button">Start using ToolImage</Link></motion.article><motion.article className="pricing-card pricing-card--pro" initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.28, delay: reduceMotion ? 0 : 0.06 }}><p className="eyebrow">TOOLIMAGE PRO / INR</p><h2>Process more.<br /><em>Do less.</em></h2><p>Batch workflows with verified access and clear INR monthly billing.</p><div className="pricing-card__price"><strong>₹149<small>/ month</small></strong><span>INR monthly subscription</span></div><ul>{proItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul>{isPro ? <Link href="/batch" className="primary-button">Start using Pro</Link> : user && configured ? <button type="button" className="primary-button" disabled={busy} onClick={() => void checkout()}>{busy ? <><LoaderCircle className="spin" size={16} /> Preparing checkout</> : <><LockKeyhole size={15} /> Upgrade to Pro</>}</button> : <ProAccessPanel compact />}{message && <p className={message.startsWith("Welcome") ? "payment-note payment-note--success" : "payment-note"} role="status">{message}</p>}<small className="payment-note">₹149/month INR. Server-side verification determines access.</small></motion.article></section><section className="pricing-note"><span>NO SURPRISES</span><i /><p>ToolImage does not use browser storage, URL parameters, or a checkout success screen as the source of Pro access.</p></section></main></SiteShell>;
}
