/** ToolImage pricing — Monochrome Instrument: verified server-side Pro access with no client-controlled purchase or entitlement state. */
import { Check, LoaderCircle, LockKeyhole } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import { Link } from "wouter";
import { ProAccessPanel } from "@/components/ProAccessPanel";
import { useEntitlement } from "@/contexts/EntitlementContext";
import { loadRazorpay } from "@/lib/razorpayCheckout";
import { SiteShell } from "@/components/SiteShell";
import { Seo } from "@/components/Seo";
import { PricingRegionSelector } from "@/components/PricingRegionSelector";
import { formatRegionalPrice, getInitialPricingRegion, PricingRegionId, REGIONAL_PRICES, setPricingRegionForSession } from "@/lib/pricing";

const freeItems = ["Single-image and target-size compression", "Single-image resizing with manual pixels", "Single-image JPG, PNG, and WebP conversion", "Standard presets and client-side processing"];
const proItems = ["Batch processing", "Custom saved presets", "Download batches as ZIP"];

export default function Pricing() {
  const [region, setRegion] = useState<PricingRegionId>(() => getInitialPricingRegion()); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const reduceMotion = useReducedMotion(); const price = formatRegionalPrice(region); const { configured, user, isPro, refresh } = useEntitlement();
  const chooseRegion = (next: PricingRegionId) => { setRegion(next); setPricingRegionForSession(next); };
  const checkout = async () => { setMessage(null); setBusy(true); try { const currentSession = await refresh(); const token = currentSession?.access_token; if (!token) throw new Error("Please reopen the email sign-in link in this browser, then try again."); const created = await fetch("/api/subscriptions/create", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ region }) }); const data = await created.json() as { error?: string; subscriptionId?: string; keyId?: string; name?: string; description?: string }; if (!created.ok || !data.subscriptionId || !data.keyId) throw new Error(data.error || "Checkout could not be prepared."); await loadRazorpay(); new window.Razorpay!({ key: data.keyId, subscription_id: data.subscriptionId, name: data.name || "ToolImage Pro", description: data.description || "Test Mode", handler: async (response) => { const verified = await fetch("/api/subscriptions/verify", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ subscriptionId: response.razorpay_subscription_id, paymentId: response.razorpay_payment_id, signature: response.razorpay_signature }) }); const result = await verified.json() as { active?: boolean; error?: string }; if (!verified.ok) { setMessage(result.error || "We could not verify this payment."); return; } await refresh(); setMessage(result.active ? "Welcome to ToolImage Pro." : "Payment verified. Your subscription is waiting for Razorpay activation."); }, modal: { ondismiss: () => setMessage("Checkout was cancelled. No Pro access was granted.") }, theme: { color: "#0d786d" } }).open(); } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout could not be started."); } finally { setBusy(false); } };
  return <SiteShell><Seo title="ToolImage Pricing — Free Local Image Tools" description="ToolImage’s core image compression, resize, and conversion tools are free and run locally in your browser." path="/pricing" noIndex /><main id="main-content"><section className="pricing-hero pricing-hero--regional"><div className="pricing-rail"><span>01</span><i /><span>CAPABILITY INDEX</span><small>TEST MODE / VERIFIED ACCESS</small></div><p className="eyebrow">SIMPLE BY DESIGN</p><h1>Useful now.<br /><em>More when it matters.</em></h1><p>Every core tool is free, works locally in your browser, and does not require an account.</p><div className="pricing-region-row"><span>Regional display</span><PricingRegionSelector region={region} onChange={chooseRegion} /></div></section><section className="pricing-cards"><motion.article className="pricing-card pricing-card--free" initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.28 }}><p className="eyebrow">AVAILABLE NOW</p><h2>Free</h2><p>For everyday image tasks.</p><div className="pricing-card__price"><strong>Free</strong><span>No account required</span></div><ul>{freeItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href="/compress-image" className="primary-button">Start using ToolImage</Link></motion.article><motion.article className="pricing-card pricing-card--pro" initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.28, delay: reduceMotion ? 0 : 0.06 }}><p className="eyebrow">TOOLIMAGE PRO / TEST MODE</p><h2>Process more.<br /><em>Do less.</em></h2><p>Batch workflows with verified access. The displayed currency is approximate and does not confirm payment availability.</p><div className="pricing-card__price"><strong>{price}<small>/ month</small></strong><span>{REGIONAL_PRICES[region].country} display price</span></div><ul>{proItems.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul>{isPro ? <Link href="/batch" className="primary-button">Start using Pro</Link> : user && configured ? <button type="button" className="primary-button" disabled={busy} onClick={() => void checkout()}>{busy ? <><LoaderCircle className="spin" size={16} /> Preparing checkout</> : <><LockKeyhole size={15} /> Upgrade to Pro</>}</button> : <ProAccessPanel compact />}{message && <p className={message.startsWith("Welcome") ? "payment-note payment-note--success" : "payment-note"} role="status">{message}</p>}<small className="payment-note">Razorpay Test Mode only. A verified server-side subscription determines access; browser locale only changes this display and no IP is collected.</small></motion.article></section><section className="pricing-note"><span>NO SURPRISES</span><i /><p>ToolImage does not use browser storage, URL parameters, or a checkout success screen as the source of Pro access.</p></section></main></SiteShell>;
}
