/** ToolImage tool pages — focused local workspaces with useful, route-specific compression guidance. */
import { ArrowRight, Check, LockKeyhole } from "lucide-react";
import { Link } from "wouter";
import { ImageStudio, StudioMode } from "@/components/ImageStudio";
import { Seo } from "@/components/Seo";
import { SiteShell } from "@/components/SiteShell";
import { PageSeo } from "@/lib/seo";
const content: Record<StudioMode, { eyebrow: string; title: React.ReactNode; description: string; notes: string[]; guideTitle: string; guide: string; path: string; seoTitle: string; seoDescription: string }> = {
  compress: { eyebrow: "TARGET-SIZE IMAGE COMPRESSOR", title: <>Fit the file.<br /><em>Keep the image.</em></>, description: "Choose exactly how small the file should be. ToolImage works through local quality and dimension passes to find a practical result.", notes: ["Target sizes from 20 KB to 2 MB", "Custom target size", "Local browser processing"], guideTitle: "How target-size compression works", guide: "Rather than applying one blunt quality setting, ToolImage checks each locally generated result and adjusts quality first. If the target still is not practical, it makes careful reductions to the image dimensions. This keeps the result as usable as possible.", path: "/compress-image", seoTitle: "Compress Images to a Target Size — Private Local Tool | ToolImage", seoDescription: "Compress JPG, PNG, and WebP images to a practical target size in your browser. No upload, account, or server-side image processing." },
  resize: { eyebrow: "IMAGE RESIZER", title: <>Find the right<br /><em>dimensions.</em></>, description: "Set width and height in pixels, preserve the original ratio, or use a useful starting point for your next post or project.", notes: ["Precise width and height", "Aspect-ratio control", "Practical social presets"], guideTitle: "Resize without distortion", guide: "When aspect ratio is enabled, changing one dimension automatically adjusts the other. Select a preset when you need a common starting size, or unlock the ratio for an exact custom canvas.", path: "/resize-image", seoTitle: "Resize Images Online — Private Browser Tool | ToolImage", seoDescription: "Resize JPG, PNG, and WebP images locally in your browser with precise dimensions, aspect-ratio control, and useful presets." },
  convert: { eyebrow: "IMAGE CONVERTER", title: <>The right<br /><em>format, locally.</em></>, description: "Move between JPG, PNG, and WebP without sending the image anywhere. Choose the file format that works for your destination.", notes: ["JPG, PNG, and WebP", "Transparency-aware export", "Immediate download"], guideTitle: "Choose the format that fits", guide: "JPG is practical for photographs, PNG maintains transparent areas, and WebP often makes a compact, modern image file. For JPG exports from transparent PNGs, ToolImage uses a clean white background.", path: "/convert-image", seoTitle: "Convert JPG, PNG, and WebP Online — Private Tool | ToolImage", seoDescription: "Convert JPG, PNG, and WebP images in your browser. ToolImage creates your chosen local file format without uploading the image." },
};
export default function ToolPage({ mode, seo }: { mode: StudioMode; seo?: PageSeo }) { const item = content[mode]; const activeTitle = seo?.title ?? item.seoTitle; const activeDescription = seo?.description ?? item.seoDescription; const activePath = seo?.path ?? item.path; const activeHeading = seo?.heading ?? item.title; const activeGuideTitle = seo?.guideTitle ?? item.guideTitle; const activeGuide = seo?.guide ?? item.guide; return <SiteShell><Seo title={activeTitle} description={activeDescription} path={activePath} schema={{ "@type": "SoftwareApplication", name: "ToolImage", applicationCategory: "MultimediaApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }} /><main id="main-content"><section className="tool-hero"><div className="hero-measure"><span>0{mode === "compress" ? 1 : mode === "resize" ? 2 : 3}</span><i /><span>{item.eyebrow}</span></div><div className="tool-hero__layout"><div><p className="eyebrow">TOOLIMAGE / {item.eyebrow}</p><h1>{activeHeading}</h1><p>{item.description}</p><ul className="tool-notes">{item.notes.map((note) => <li key={note}><Check size={15} /> {note}</li>)}</ul></div><div className="tool-hero__local"><LockKeyhole size={19} /><p><strong>Private by design.</strong><br />Your file is processed in this browser and remains on your device.</p></div></div></section><section className="tool-section tool-section--page"><ImageStudio mode={mode} initialTargetBytes={seo?.targetBytes} /></section><section className="guide-section"><div><p className="eyebrow">A LITTLE CONTEXT</p><h2>{activeGuideTitle}</h2></div><div><p>{activeGuide}</p>{seo?.detail && <p className="guide-detail">{seo.detail}</p>}<Link href="/" className="text-link">Explore all tools <ArrowRight size={16} /></Link></div></section></main></SiteShell>; }
