/** ToolImage tool pages — Monochrome Instrument: direct local workspaces with brief, practical editorial guidance. */
import { ArrowRight, Check, LockKeyhole } from "lucide-react";
import { Link } from "wouter";
import { ImageStudio, StudioMode } from "@/components/ImageStudio";
import { SiteShell } from "@/components/SiteShell";

const content: Record<StudioMode, { eyebrow: string; title: React.ReactNode; description: string; notes: string[]; guideTitle: string; guide: string }> = {
  compress: { eyebrow: "TARGET-SIZE IMAGE COMPRESSOR", title: <>Fit the file.<br /><em>Keep the image.</em></>, description: "Choose exactly how small the file should be. ToolImage works through local quality and dimension passes to find a practical result.", notes: ["Target sizes from 20 KB to 2 MB", "Custom target size", "Local browser processing"], guideTitle: "How target-size compression works", guide: "Rather than applying one blunt quality setting, ToolImage checks each locally generated result and adjusts quality first. If the target still is not practical, it makes careful reductions to the image dimensions. This keeps the result as usable as possible." },
  resize: { eyebrow: "IMAGE RESIZER", title: <>Find the right<br /><em>dimensions.</em></>, description: "Set width and height in pixels, preserve the original ratio, or use a useful starting point for your next post or project.", notes: ["Precise width and height", "Aspect-ratio control", "Practical social presets"], guideTitle: "Resize without distortion", guide: "When aspect ratio is enabled, changing one dimension automatically adjusts the other. Select a preset when you need a common starting size, or unlock the ratio for an exact custom canvas." },
  convert: { eyebrow: "IMAGE CONVERTER", title: <>The right<br /><em>format, locally.</em></>, description: "Move between JPG, PNG, and WebP without sending the image anywhere. Choose the file format that works for your destination.", notes: ["JPG, PNG, and WebP", "Transparency-aware export", "Immediate download"], guideTitle: "Choose the format that fits", guide: "JPG is practical for photographs, PNG maintains transparent areas, and WebP often makes a compact, modern image file. For JPG exports from transparent PNGs, ToolImage uses a clean white background." },
};

export default function ToolPage({ mode }: { mode: StudioMode }) {
  const item = content[mode];
  return <SiteShell><main><section className="tool-hero"><div className="hero-measure"><span>0{mode === "compress" ? 1 : mode === "resize" ? 2 : 3}</span><i /><span>{item.eyebrow}</span></div><div className="tool-hero__layout"><div><p className="eyebrow">TOOLIMAGE / {item.eyebrow}</p><h1>{item.title}</h1><p>{item.description}</p><ul className="tool-notes">{item.notes.map((note) => <li key={note}><Check size={15} /> {note}</li>)}</ul></div><div className="tool-hero__local"><LockKeyhole size={19} /><p><strong>Private by design.</strong><br />Your file is processed in this browser and remains on your device.</p></div></div></section><section className="tool-section tool-section--page"><ImageStudio mode={mode} /></section><section className="guide-section"><div><p className="eyebrow">A LITTLE CONTEXT</p><h2>{item.guideTitle}</h2></div><div><p>{item.guide}</p><Link href="/" className="text-link">Explore all tools <ArrowRight size={16} /></Link></div></section></main></SiteShell>;
}
