/** ToolImage Pro access panel — Monochrome Instrument account gate with clear, secure same-browser Magic Link completion. */
import { Check, LoaderCircle, LockKeyhole, Mail, LogOut, RefreshCw } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { useEntitlement } from "@/contexts/EntitlementContext";

export function ProAccessPanel({ compact = false }: { compact?: boolean }) {
  const { configured, loading, user, isPro, status, refresh, sendMagicLink, signOut } = useEntitlement();
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState<string | null>(null); const [sending, setSending] = useState(false); const [checking, setChecking] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setSending(true); try { await sendMagicLink(email); setSent(true); } catch (issue) { setError(issue instanceof Error ? issue.message : "We could not send that sign-in link."); } finally { setSending(false); } };
  const checkSession = async () => { setError(null); setChecking(true); try { const next = await refresh(); if (!next) setError("This browser is not signed in yet. Open the email link in this same browser, then return here."); } catch (issue) { setError(issue instanceof Error ? issue.message : "We could not refresh secure access."); } finally { setChecking(false); } };
  if (loading) return <section className="pro-access-panel" aria-live="polite"><LoaderCircle className="spin" size={18} /><p>Checking secure account access…</p></section>;
  if (!configured) return <section className="pro-access-panel"><LockKeyhole size={19} /><div><p className="eyebrow">TOOLIMAGE PRO</p><h2>Secure access is being configured.</h2><p>Free image tools remain available without an account.</p></div></section>;
  if (isPro) return <section className="pro-access-panel pro-access-panel--active"><Check size={19} /><div><p className="eyebrow">TOOLIMAGE PRO ACTIVE</p><h2>{status === "grace" ? "Your billing period remains active." : "Welcome to ToolImage Pro."}</h2><p>Batch processing, custom presets, and ZIP downloads are available in this browser session.</p></div></section>;
  if (user) return <section className="pro-access-panel"><LockKeyhole size={19} /><div><p className="eyebrow">TOOLIMAGE PRO</p><h2>Process multiple images at once.</h2><p>Batch processing, custom presets, and ZIP downloads are available after a verified Pro subscription.</p><Link href="/pricing" className="primary-button">Upgrade to Pro</Link><button type="button" className="text-button" onClick={() => void signOut()}><LogOut size={14} /> Sign out</button></div></section>;
  return <section className={`pro-access-panel ${compact ? "pro-access-panel--compact" : ""}`}><Mail size={19} /><div><p className="eyebrow">TOOLIMAGE PRO</p><h2>Process multiple images at once.</h2><p>Sign in with your email before starting a secure Test Mode subscription.</p>{sent ? <><p className="pro-access-panel__sent"><Check size={15} /> Email sent. Open its sign-in link in this same browser, then return here.</p><p>Opening the link in another browser signs in only that browser. ToolImage never transfers sessions or tokens between browsers.</p><button type="button" className="primary-button" onClick={() => void checkSession()} disabled={checking}>{checking ? <LoaderCircle className="spin" size={16} /> : <RefreshCw size={16} />} I opened the link here</button><button type="button" className="text-button" onClick={() => { setSent(false); setError(null); }}>Use a different email</button></> : <form onSubmit={submit} className="pro-access-form"><label className="sr-only" htmlFor="pro-email">Email address</label><input id="pro-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /><button className="primary-button" type="submit" disabled={sending}>{sending ? <LoaderCircle className="spin" size={16} /> : <Mail size={16} />} Email sign-in link</button></form>}{error && <p className="form-error" role="alert">{error}</p>}</div></section>;
}
