import { FormEvent, RefObject, useEffect, useRef, useState } from "react";
import { LoaderCircle, Send, X } from "lucide-react";
import { SUPPORT_ISSUE_TYPES, SupportIssueType, validateSupportSubmission } from "../../../shared/support";

type SupportModalProps = { open: boolean; onClose: () => void; returnFocusRef: RefObject<HTMLButtonElement | null>; };
const firstIssueType = SUPPORT_ISSUE_TYPES[0];

export function SupportModal({ open, onClose, returnFocusRef }: SupportModalProps) {
  const dialogRef = useRef<HTMLDivElement>(null); const closeRef = useRef<HTMLButtonElement>(null);
  const [email, setEmail] = useState(""); const [issueType, setIssueType] = useState<SupportIssueType>(firstIssueType); const [description, setDescription] = useState(""); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!open) return; const frame = window.requestAnimationFrame(() => closeRef.current?.focus()); const onKeyDown = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); returnFocusRef.current?.focus(); onClose(); return; } if (event.key !== "Tab") return; const focusable = dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href]'); if (!focusable?.length) return; const items = Array.from(focusable); const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener("keydown", onKeyDown); return () => { window.cancelAnimationFrame(frame); window.removeEventListener("keydown", onKeyDown); }; }, [onClose, open]);
  useEffect(() => { if (open) { setError(null); setSuccess(false); } }, [open]);
  const close = () => { returnFocusRef.current?.focus(); onClose(); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(null); setSuccess(false); const parsed = validateSupportSubmission({ email, issueType, description, pageUrl: window.location.href, browser: navigator.userAgent }); if ("error" in parsed) { setError(parsed.error ?? "Please check the form and try again."); return; } setBusy(true); try { const response = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...parsed.value, pageUrl: window.location.href, browser: navigator.userAgent }) }); const body = await response.json().catch(() => ({})) as { error?: string; delivered?: boolean }; if (!response.ok || !body.delivered) throw new Error(body.error || "We could not deliver your report right now. Please try again later."); setEmail(""); setIssueType(firstIssueType); setDescription(""); setSuccess(true); } catch (issue) { setError(issue instanceof Error ? issue.message : "We could not deliver your report right now. Please try again later."); } finally { setBusy(false); } };
  if (!open) return null;
  return <div className="support-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><div className="support-modal" ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="support-modal-title" aria-describedby="support-modal-description"><button ref={closeRef} type="button" className="support-modal__close" onClick={close} aria-label="Close contact and support form"><X size={18} /></button><p className="eyebrow">TOOLIMAGE / CONTACT &amp; SUPPORT</p><h2 id="support-modal-title">Tell us what went wrong</h2><p id="support-modal-description">Found a bug or having an issue? Tell us what happened and we’ll look into it.</p>{success ? <div className="support-success" role="status"><strong>Report received.</strong><span>Thanks for helping us improve ToolImage. We’ll review your report.</span></div> : <form className="support-form" onSubmit={submit} noValidate><label><span>What went wrong?</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} minLength={20} maxLength={5_000} required placeholder="Include what you expected, what happened, and any safe steps to reproduce it." /></label><label><span>Your email</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" maxLength={320} required placeholder="you@example.com" /></label><label><span>Issue type</span><select value={issueType} onChange={(event) => setIssueType(event.target.value as SupportIssueType)}>{SUPPORT_ISSUE_TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><p className="support-form__privacy">Do not include passwords, access tokens, payment-card details, CVV values, UPI PINs, private image contents, or other sensitive credentials.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="support-form__actions"><button className="secondary-button" type="button" onClick={close}>Cancel</button><button className="primary-button" type="submit" disabled={busy}>{busy ? <><LoaderCircle className="spin" size={16} /> Sending</> : <><Send size={16} /> Submit report</>}</button></div></form>}</div></div>;
}
